name: Application Build and Deploy

on: 
  push:
    branches: [test-action]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
          
      - name: Build Project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
