name: Application Build and Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
     
jobs:
  build:
    name: Build and Commit
    runs-on: ubuntu-latest
    env:
      MAPBOX_PUBLIC_KEY: ${{ secrets.MAPBOX_PUBLIC_KEY }}
      REF: ${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master
        
      - name: Application Setup
        run: sh build/setup.sh <<< "$MAPBOX_PUBLIC_KEY"
        
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
          
      - name: Compile Languages
        run: yarn run i18n-compile
          
      - name: Build Project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
          
      - name: Push master to GitHub & Push dist subtree
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch
          git add .
          git commit -m "Build Release $REF"
          git push
          git subtree push --prefix dist origin dist
          
