name: Application Build and Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
     
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      MAPBOX_PUBLIC_KEY: ${{ secrets.MAPBOX_PUBLIC_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Application Setup
        run: sh build/setup.sh <<< "$MAPBOX_PUBLIC_KEY"
        
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
          
      - name: Compile Languages
        run: yarn run i18n-compile
          
      - name: Build Project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
          
      - name: Commit Build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.ref }}
