name: Application Build and Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master # Push events to matching v*, i.e. v1.0, v20.15.10
     
jobs:
  build:
    name: Push Dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Add api remote origin
        run: |
          git remote add rdist https://github.com/systragroup/quetzal-network-editor.git
          git pull rdist dist
          git subtree push --prefix dist rdist dist
